### ISSUE TITLE
Problem installing node-dht-sensor

### ISSUE THREAD

**Issue by MikhailKrasnobaev** [openhomeautomation/rpi-web-control#2]
Hi, thanks a lot for this project!
For some reason I had a problem installing node-dht-sensor using npm,
helped installing it directly from git.

Hope this info helps those installing.

**Comment by makecademy** [comment]
Hello, thanks for letting me know! Can you explain how you did it directly from Git? Then I'll close this issue and insert the tip directly in the blog article. Thanks!

**Comment by MikhailKrasnobaev** [comment]
Yes, sure.
Basically I got an error after this step _sudo npm install node-dht-sensor express pi-arest jade_
Error was about node-dht-sensor.
So I ran  _sudo npm install https://github.com/momenso/node-dht-sensor.git_
That's it :)
